[package]
name = "silk-chiffon-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description = "Format-independent processing for Silk Chiffon"

[dependencies]
anyhow.workspace = true
arrow.workspace = true
async-trait.workspace = true
bytes = "^1.12.1"
camino = "^1.2.4"
clap.workspace = true
datafusion.workspace = true
futures.workspace = true
object_store.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
silk-chiffon-storage = { path = "../silk-chiffon-storage", default-features = false }
strum_macros = "^0.28.0"
sysinfo = "^0.39.6"
tempfile = "^3.27.0"
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
chrono = "^0.4.45"
datafusion-datasource = "=54.1.0"
silk-chiffon-storage = { path = "../silk-chiffon-storage", features = ["local"] }
silk-chiffon-test-support = { path = "../silk-chiffon-test-support" }

[lints]
workspace = true
